ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.durgagopalakrishna.online
REDIS_HOST: redis-dev.durgagopalakrishna.online
MYSQL_HOST: mysql-dev.durgagopalakrishna.online
RABBITMQ_HOST: rabbitmq-dev.durgagopalakrishna.online
CATALOGUE_HOST: catalogue-dev.durgagopalakrishna.online
USER_HOST: user-dev.durgagopalakrishna.online
CART_HOST: cart-dev.durgagopalakrishna.online
SHIPPING_HOST: shipping-dev.durgagopalakrishna.online
PAYMENT_HOST: payment-dev.durgagopalakrishna.online