[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.durgagopalakrishna.online

[redis]
localhost

[user]
user-dev.durgagopalakrishna.online

[cart]
cart-dev.durgagopalakrishna.online

[mysql]
mysql-dev.durgagopalakrishna.online

[shipping]
shipping-dev.durgagopalakrishna.online

[rabbitmq]
rabbitmq-dev.durgagopalakrishna.online

[payment]
payment-dev.durgagopalakrishna.online

[frontend]
frontend-dev.durgagopalakrishna.online
